### ISSUE TITLE
btoa() doesn't work in node

### ISSUE THREAD

**Issue by theaquarium** [stewartlord/identicon.js#42]

**Comment by theaquarium** [comment]
This is if you need base64 SVGs

**Comment by stewartlord** [comment]
Thanks for the report! I will try to fix this shortly :+1:

**Comment by buildbreakdo** [comment]
@aquariumpain Base64 of SVG increases the size by 33%, would avoid if you can. SVG can be displayed as an SVG element like an img and can be set as a background-image via CSS.

Great article on the topic:
https://css-tricks.com/probably-dont-base64-svg/

**Comment by theaquarium** [comment]
@buildbreakdo I am familiar with this thanks to your previous comments on other issues. I use this, however if someone needs base64 SVG, it throws an error from inside the module which should never be the case.

**Comment by stewartlord** [comment]
@aquariumpain could you try out the fix in #44 and let me know if it works for you?

**Comment by ghost** [comment]
There is still a problem with it:

```
btoa is not defined
    at Svg.getBase64 (/Users/maxblock/projects/ptracker/node_modules/identicon.js/identicon.js:190:13)
    at Identicon.toString (/Users/maxblock/projects/ptracker/node_modules/identicon.js/identicon.js:133:38)
    at model.avatar (/Users/maxblock/projects/ptracker/src/models/User.ts:32:45)
    at VirtualType.applyGetters (/Users/maxblock/projects/ptracker/node_modules/mongoose/lib/virtualtype.js:77:25)
    at model.Document.get (/Users/maxblock/projects/ptracker/node_modules/mongoose/lib/document.js:1035:19)
```

**Comment by stewartlord** [comment]
Sorry guys looks like I forgot to merge my fix last year :man_facepalming:

**Comment by stewartlord** [comment]
The fix should be live now. Please let me know if you find any other issues. Much appreciated :smile:

**Comment by qoter** [comment]
@stewartlord It's still not work, node.js throws exception because `btoa` is not `defined` (`btoa` is not `undefined`, node.js can't interprets it)
